In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [2]:
!ssh-keygen -t rsa -b 4096

Generating public/private rsa key pair.
Enter file in which to save the key (/root/.ssh/id_rsa):
Created directory '/root/.ssh'.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /root/.ssh/id_rsa
Your public key has been saved in /root/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:FxIEUuKTd1r0nA1mdkhhuYJtCQt1S7BSTKuS7cN6Xow root@7325355b63f5
The key's randomart image is:
+---[RSA 4096]----+
|    o=B+*.O+.    |
|   ..=o* Xo=     |
|    =.+==.=..    |
|   o =o+=...     |
|  o o ..S..      |
|   + o   .       |
|    E o          |
|   ..o           |
|  .o.            |
+----[SHA256]-----+

In [3]:
!ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

# github.com:22 SSH-2.0-1581bab2

In [4]:
!cat /root/.ssh/id_rsa.pub

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCjMRfYjpWRj7OYL2uzFVflx+90CGYZ41WGGaYA0wR8eqscMKuulYr+6Ef+p1zaQPRlR0z3cpfwXDqYRM3zksUyRZRTaHF93IJMTZtxPvR88bUaXl0rRFC3U0u9F1fWQR7gaNbHZYY6oU4Nufq5zwvmV4xAXfe8NTDsQu0HQBt2nuuwI+tmFD3xtZbYHy+YDVJKR2GuNepCHbtFwKYLcIerHNu/hpnxn6c7+NpLvP0PDL53ln987uWjqRouzziqkFc0NhVMXruEF68pFwG63IE+vAFeEiupsTzJIWdISYWc+2k0BJpAtmwJnZUi0uePgoHdfCeXwGfn70e+9dF1IndoPxOjUClVMBZNIrOMIHAUa9+f5jDHS893zGpKLd1TB9ukOBEI+6u7bnGVvgomuUhstPNEfylI4CuktXKUpRGTdwGuneGkSOrqVOC2PQOTyO9p7BRuWR6zY8oR4jl2eSeeB20BZEdZkfBQphYAVaYdXMQ1Sc9UfokplwkWn/e9h7DbttRYc/rcSx8iPif1p8EvYWEUcmZeVXFuYYjvOmrEcf0+dekCEZePBXI4VD7R+Qk0rrhm88f1bJHZVnhp99nQ2g2iF0QzVNRLPmyj7dfvX0sYLjkiTGfh5tFY77YoibAPvFz/PaiN0Hgvf5CCFTYmUDbzj75u3cdAErhh91ebZw== root@7325355b63f5

In [6]:
!ssh -T git@github.com

Hi abolfazlaghdaee! You've successfully authenticated, but GitHub does not provide shell access.

In [7]:
!git config --global user.email "abolfazlaghdaee@gmail.com"
!git config --global user.name "abolfazl"

In [8]:
!git clone git@github.com:abolfazlaghdaee/Irony_Detection.git

Cloning into 'Irony_Detection'...
remote: Enumerating objects: 154, done.
remote: Total 154 (delta 0), reused 0 (delta 0), pack-reused 154 (from 1)
Receiving objects: 100% (154/154), 88.76 MiB | 52.69 MiB/s, done.
Resolving deltas: 100% (77/77), done.

In [9]:
!ls

Irony_Detection  sample_data

In [10]:
%cd Irony_Detection/phase2

/content/Irony_Detection/phase2

In [11]:
import pandas as pd
df = pd.read_csv('data/cleaned_data.csv')

In [12]:
df.head()

,Text,Target,clened_text
0,سجاد غریبی بیشتر بدرد خندوانه میخوره × نولان...,1,سجاد غریبی بدرد خندوانه میخوره نولانی
1,کاش سجاد غریبی رو ممنون الخروج کنن که دیگه نتو...,1,کاش سجاد غریبی ممنون الخروج کنن دیگه نتونه بره...
2,میگن سجاد غریبی وسطای مسابقه گفته: قبول نیس، ا...,2,میگن سجاد غریبی وسطای مسابقه قبول نیس مشت میزنه
3,به کیسه بوکس مشت میزنی برمیگرده، سجاد غریبی می...,1,کیسه بوکس مشت می‌زنی برمیگرده سجاد غریبی می‌رف...
4,‏اگه جای سجاد غریبی بودم حالا که کتکه رو خورده...,1,اگه سجاد غریبی بودم کتکه خوردهم فورا گرفتن دیه...

In [13]:
df['Target'].value_counts()

Target
3    9335
1    8757
2    7830
Name: count, dtype: int64

In [14]:
df = df.dropna(subset=['clened_text'])

In [15]:
df.isnull().sum()

Text           0
Target         0
clened_text    0
dtype: int64

In [16]:
X = df['clened_text']
y = df['Target']

In [17]:
tf_idf = TfidfVectorizer(max_features=5000, ngram_range=(1, 3))

In [18]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
x_train_tfidf = tf_idf.fit_transform(x_train)
x_test_tfidf = tf_idf.transform(x_test)

In [20]:
models = {
    'Logistic Regression': LogisticRegression(),
    'SVC': SVC(),
    'Random Forest': RandomForestClassifier(),
    'KNN': KNeighborsClassifier(),

}

In [21]:
def cacl_metrics(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print(classification_report(y_test, y_pred))
    print('Accuracy: ',   accuracy_score(y_test, y_pred))

In [ ]:
for model_name, model in models.items():
    print(f"Model: {model_name}")
    cacl_metrics(model, x_train_tfidf, x_test_tfidf, y_train, y_test)

    print("-"*100)

Model: Logistic Regression

/home/abolfazl/anaconda3/envs/ML/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

              precision    recall  f1-score   support

           1       0.54      0.60      0.57      1789
           2       0.33      0.24      0.28      1524
           3       0.52      0.59      0.56      1872

    accuracy                           0.49      5185
   macro avg       0.47      0.48      0.47      5185
weighted avg       0.47      0.49      0.48      5185

Accuracy:  0.4896817743490839
----------------------------------------------------------------------------------------------------
Model: SVC
              precision    recall  f1-score   support

           1       0.54      0.65      0.59      1789
           2       0.35      0.18      0.24      1524
           3       0.53      0.64      0.58      1872

    accuracy                           0.51      5185
   macro avg       0.47      0.49      0.47      5185
weighted avg       0.48      0.51      0.48      5185

Accuracy:  0.5064609450337512
----------------------------------------------------------------------------------------------------
Model: Random Forest
              precision    recall  f1-score   support

           1       0.54      0.58      0.56      1789
           2       0.34      0.13      0.18      1524
           3       0.49      0.71      0.58      1872

    accuracy                           0.49      5185
   macro avg       0.46      0.47      0.44      5185
weighted avg       0.46      0.49      0.46      5185

Accuracy:  0.49373191899710706
----------------------------------------------------------------------------------------------------
Model: KNN
              precision    recall  f1-score   support

           1       0.34      0.99      0.51      1789
           2       0.24      0.00      0.01      1524
           3       0.38      0.00      0.00      1872

    accuracy                           0.34      5185
   macro avg       0.32      0.33      0.17      5185
weighted avg       0.33      0.34      0.18      5185

Accuracy:  0.3434908389585342
----------------------------------------------------------------------------------------------------

### ParsBert Embedings

In [22]:
%cd ..

/content/Irony_Detection

In [23]:
!ls

data  Embeddings  LICENSE  model  phase2  Preprocesing.ipynb  README.md

In [24]:
from Embeddings.parsbert_embedding import get_parsbert_embeddings

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/434 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/654M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/654M [00:00<?, ?B/s]

In [25]:
x_train_partbert = get_parsbert_embeddings(x_train)

Embedding sentences:   0%|          | 0/648 [00:00<?, ?it/s]/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Embedding sentences:   0%|          | 1/648 [00:04<51:57,  4.82s/it]
Embedding sentences:   0%|          | 2/648 [00:09<49:51,  4.63s/it]
Embedding sentences:   0%|          | 3/648 [00:19<1:16:07,  7.08s/it]
Embedding sentences:   1%|          | 4/648 [00:29<1:27:31,  8.15s/it]
Embedding sentences:   1%|          | 5/648 [00:32<1:09:48,  6.51s/it]
Embedding sentences:   1%|          | 6/648 [00:38<1:07:06,  6.27s/it]
Embedding sentences:   1%|          | 7/648 [00:42<59:03,  5.53s/it]
Embedding sentences:   1%|          | 8/648 [00:45<51:43,  4.85s/it]
Embedding sentences:   1%|▏         | 9/648 [00:54<1:04:48,  6.09s/it]
Embedding sentences:   2%|▏         | 10/648 [00:58<57:32,  5.41s/it]
Embedding sentences:   2%|▏         | 11/648 [01:06<1:05:12,  6.14s/it]
Embedding sentences:   2%|▏         | 12/648 [01:10<59:29,  5.61s/it]
Embedding sentences:   2%|▏         | 13/648 [01:14<51:58,  4.91s/it]
Embedding sentences:   2%|▏         | 14/648 [01:20<57:35,  5.45s/it]
Embedding sentences:   2%|▏         | 15/648 [01:23<50:02,  4.74s/it]
Embedding sentences:   2%|▏         | 16/648 [01:30<55:51,  5.30s/it]
Embedding sentences:   3%|▎         | 17/648 [01:33<48:47,  4.64s/it]
Embedding sentences:   3%|▎         | 18/648 [01:37<45:26,  4.33s/it]
Embedding sentences:   3%|▎         | 19/648 [01:44<55:01,  5.25s/it]
Embedding sentences:   3%|▎         | 20/648 [01:47<48:30,  4.63s/it]
Embedding sentences:   3%|▎         | 21/648 [01:53<52:04,  4.98s/it]
Embedding sentences:   3%|▎         | 22/648 [01:57<47:59,  4.60s/it]
Embedding sentences:   4%|▎         | 23/648 [02:00<43:31,  4.18s/it]
Embedding sentences:   4%|▎         | 24/648 [02:03<40:24,  3.89s/it]
Embedding sentences:   4%|▍         | 25/648 [02:11<51:36,  4.97s/it]
Embedding sentences:   4%|▍         | 26/648 [02:14<45:41,  4.41s/it]
Embedding sentences:   4%|▍         | 27/648 [02:17<43:07,  4.17s/it]
Embedding sentences:   4%|▍         | 28/648 [02:21<42:13,  4.09s/it]
Embedding sentences:   4%|▍         | 29/648 [02:26<43:44,  4.24s/it]
Embedding sentences:   5%|▍         | 30/648 [02:30<43:32,  4.23s/it]
Embedding sentences:   5%|▍         | 31/648 [02:36<48:20,  4.70s/it]
Embedding sentences:   5%|▍         | 32/648 [02:39<44:14,  4.31s/it]
Embedding sentences:   5%|▌         | 33/648 [02:45<48:26,  4.73s/it]
Embedding sentences:   5%|▌         | 34/648 [02:49<44:36,  4.36s/it]
Embedding sentences:   5%|▌         | 35/648 [02:52<41:17,  4.04s/it]
Embedding sentences:   6%|▌         | 36/648 [02:56<40:10,  3.94s/it]
Embedding sentences:   6%|▌         | 37/648 [02:59<38:28,  3.78s/it]
Embedding sentences:   6%|▌         | 38/648 [03:02<37:33,  3.69s/it]
Embedding sentences:   6%|▌         | 39/648 [03:08<44:12,  4.36s/it]
Embedding sentences:   6%|▌         | 40/648 [03:12<42:45,  4.22s/it]
Embedding sentences:   6%|▋         | 41/648 [03:17<42:55,  4.24s/it]
Embedding sentences:   6%|▋         | 42/648 [03:21<42:43,  4.23s/it]
Embedding sentences:   7%|▋         | 43/648 [03:25<42:15,  4.19s/it]
Embedding sentences:   7%|▋         | 44/648 [03:34<55:48,  5.54s/it]
Embedding sentences:   7%|▋         | 45/648 [03:40<59:29,  5.92s/it]
Embedding sentences:   7%|▋         | 46/648 [03:45<54:49,  5.46s/it]
Embedding sentences:   7%|▋         | 47/648 [03:48<48:31,  4.85s/it]
Embedding sentences:   7%|▋         | 48/648 [03:57<1:00:54,  6.09s/it]
Embedding sentences:   8%|▊         | 49/648 [04:05<1:07:25,  6.75s/it]
Embedding sentences:   8%|▊         | 50/648 [04:09<57:00,  5.72s/it]
Embedding sentences:   8%|▊         | 51/648 [04:14<54:27,  5.47s/it]
Embedding sentences:   8%|▊         | 52/648 [04:19<52:39,  5.30s/it]
Embedding sentences:   8%|▊         | 53/648 [04:25<55:14,  5.57s/it]
Embedding sentences:   8%|▊         | 54/648 [04:33<1:03:15,  6.39s/it]
Embedding sentences:   8%|▊         | 55/648 [04:41<1:07:54,  6.87s/it]
Embedding sentences:   9%|▊         | 56/648 [04:46<1:01:40,  6.25s/it]
Embedding sentences:   9%|▉         | 57/648 [04:49<52:51,  5.37s/it]
Embedding sentences:   9%|▉         | 58/648 [04:54<49:54,  5.08s/it]
Embedding sentences:   9%|▉         | 59/648 [05:00<53:07,  5.41s/it]
Embedding sentences:   9%|▉         | 60/648 [05:03<48:00,  4.90s/it]
Embedding sentences:   9%|▉         | 61/648 [05:06<42:04,  4.30s/it]
Embedding sentences:  10%|▉         | 62/648 [05:11<43:09,  4.42s/it]
Embedding sentences:  10%|▉         | 63/648 [05:14<40:06,  4.11s/it]
Embedding sentences:  10%|▉         | 64/648 [05:21<46:24,  4.77s/it]
Embedding sentences:  10%|█         | 65/648 [05:24<41:28,  4.27s/it]
Embedding sentences:  10%|█         | 66/648 [05:27<38:18,  3.95s/it]
Embedding sentences:  10%|█         | 67/648 [05:30<36:21,  3.75s/it]
Embedding sentences:  10%|█         | 68/648 [05:34<35:50,  3.71s/it]
Embedding sentences:  11%|█         | 69/648 [05:37<34:53,  3.62s/it]
Embedding sentences:  11%|█         | 70/648 [05:40<33:19,  3.46s/it]
Embedding sentences:  11%|█         | 71/648 [05:44<34:15,  3.56s/it]
Embedding sentences:  11%|█         | 72/648 [05:51<43:31,  4.53s/it]
Embedding sentences:  11%|█▏        | 73/648 [05:55<40:28,  4.22s/it]
Embedding sentences:  11%|█▏        | 74/648 [06:03<53:32,  5.60s/it]
Embedding sentences:  12%|█▏        | 75/648 [06:07<46:34,  4.88s/it]
Embedding sentences:  12%|█▏        | 76/648 [06:10<41:07,  4.31s/it]
Embedding sentences:  12%|█▏        | 77/648 [06:13<38:09,  4.01s/it]
Embedding sentences:  12%|█▏        | 78/648 [06:19<42:54,  4.52s/it]
Embedding sentences:  12%|█▏        | 79/648 [06:22<40:14,  4.24s/it]
Embedding sentences:  12%|█▏        | 80/648 [06:29<47:08,  4.98s/it]
Embedding sentences:  12%|█▎        | 81/648 [06:36<53:03,  5.61s/it]
Embedding sentences:  13%|█▎        | 82/648 [06:39<46:07,  4.89s/it]
Embedding sentences:  13%|█▎        | 83/648 [06:48<56:49,  6.03s/it]
Embedding sentences:  13%|█▎        | 84/648 [06:51<48:26,  5.15s/it]
Embedding sentences:  13%|█▎        | 85/648 [06:54<41:27,  4.42s/it]
Embedding sentences:  13%|█▎        | 86/648 [06:58<41:36,  4.44s/it]
Embedding sentences:  13%|█▎        | 87/648 [07:07<54:19,  5.81s/it]
Embedding sentences:  14%|█▎        | 88/648 [07:12<51:23,  5.51s/it]
Embedding sentences:  14%|█▎        | 89/648 [07:19<56:01,  6.01s/it]
Embedding sentences:  14%|█▍        | 90/648 [07:23<50:52,  5.47s/it]
Embedding sentences:  14%|█▍        | 91/648 [07:28<47:14,  5.09s/it]
Embedding sentences:  14%|█▍        | 92/648 [07:33<47:12,  5.09s/it]
Embedding sentences:  14%|█▍        | 93/648 [07:35<40:11,  4.35s/it]
Embedding sentences:  15%|█▍        | 94/648 [07:40<40:16,  4.36s/it]
Embedding sentences:  15%|█▍        | 95/648 [07:44<40:17,  4.37s/it]
Embedding sentences:  15%|█▍        | 96/648 [07:47<36:42,  3.99s/it]
Embedding sentences:  15%|█▍        | 97/648 [07:50<34:44,  3.78s/it]
Embedding sentences:  15%|█▌        | 98/648 [07:54<33:37,  3.67s/it]
Embedding sentences:  15%|█▌        | 99/648 [07:57<32:16,  3.53s/it]
Embedding sentences:  15%|█▌        | 100/648 [08:04<41:11,  4.51s/it]
Embedding sentences:  16%|█▌        | 101/648 [08:08<39:26,  4.33s/it]
Embedding sentences:  16%|█▌        | 102/648 [08:14<44:29,  4.89s/it]
Embedding sentences:  16%|█▌        | 103/648 [08:17<39:48,  4.38s/it]
Embedding sentences:  16%|█▌        | 104/648 [08:23<43:35,  4.81s/it]
Embedding sentences:  16%|█▌        | 105/648 [08:26<39:08,  4.33s/it]
Embedding sentences:  16%|█▋        | 106/648 [08:31<41:42,  4.62s/it]
Embedding sentences:  17%|█▋        | 107/648 [08:37<45:22,  5.03s/it]
Embedding sentences:  17%|█▋        | 108/648 [08:46<54:39,  6.07s/it]
Embedding sentences:  17%|█▋        | 109/648 [08:50<50:18,  5.60s/it]
Embedding sentences:  17%|█▋        | 110/648 [08:53<43:13,  4.82s/it]
Embedding sentences:  17%|█▋        | 111/648 [09:00<48:43,  5.44s/it]
Embedding sentences:  17%|█▋        | 112/648 [09:07<50:39,  5.67s/it]
Embedding sentences:  17%|█▋        | 113/648 [09:10<43:57,  4.93s/it]
Embedding sentences:  18%|█▊        | 114/648 [09:13<38:59,  4.38s/it]
Embedding sentences:  18%|█▊        | 115/648 [09:16<35:13,  3.97s/it]
Embedding sentences:  18%|█▊        | 116/648 [09:19<33:23,  3.77s/it]
Embedding sentences:  18%|█▊        | 117/648 [09:25<37:56,  4.29s/it]
Embedding sentences:  18%|█▊        | 118/648 [09:28<34:59,  3.96s/it]
Embedding sentences:  18%|█▊        | 119/648 [09:35<43:29,  4.93s/it]
Embedding sentences:  19%|█▊        | 120/648 [09:40<43:34,  4.95s/it]
Embedding sentences:  19%|█▊        | 121/648 [09:44<40:43,  4.64s/it]
Embedding sentences:  19%|█▉        | 122/648 [09:50<43:58,  5.02s/it]
Embedding sentences:  19%|█▉        | 123/648 [09:55<45:09,  5.16s/it]
Embedding sentences:  19%|█▉        | 124/648 [09:59<41:31,  4.75s/it]
Embedding sentences:  19%|█▉        | 125/648 [10:02<37:21,  4.29s/it]
Embedding sentences:  19%|█▉        | 126/648 [10:05<33:09,  3.81s/it]
Embedding sentences:  20%|█▉        | 127/648 [10:11<38:00,  4.38s/it]
Embedding sentences:  20%|█▉        | 128/648 [10:15<38:15,  4.42s/it]
Embedding sentences:  20%|█▉        | 129/648 [10:18<35:02,  4.05s/it]
Embedding sentences:  20%|██        | 130/648 [10:27<47:00,  5.44s/it]
Embedding sentences:  20%|██        | 131/648 [10:30<41:07,  4.77s/it]
Embedding sentences:  20%|██        | 132/648 [10:39<50:23,  5.86s/it]
Embedding sentences:  21%|██        | 133/648 [10:42<44:43,  5.21s/it]
Embedding sentences:  21%|██        | 134/648 [10:51<53:21,  6.23s/it]
Embedding sentences:  21%|██        | 135/648 [10:54<45:13,  5.29s/it]
Embedding sentences:  21%|██        | 136/648 [10:58<41:20,  4.84s/it]
Embedding sentences:  21%|██        | 137/648 [11:03<41:08,  4.83s/it]
Embedding sentences:  21%|██▏       | 138/648 [11:07<40:28,  4.76s/it]
Embedding sentences:  21%|██▏       | 139/648 [11:11<38:26,  4.53s/it]
Embedding sentences:  22%|██▏       | 140/648 [11:14<34:13,  4.04s/it]
Embedding sentences:  22%|██▏       | 141/648 [11:17<31:46,  3.76s/it]
Embedding sentences:  22%|██▏       | 142/648 [11:22<33:50,  4.01s/it]
Embedding sentences:  22%|██▏       | 143/648 [11:27<35:15,  4.19s/it]
Embedding sentences:  22%|██▏       | 144/648 [11:30<33:42,  4.01s/it]
Embedding sentences:  22%|██▏       | 145/648 [11:34<34:20,  4.10s/it]
Embedding sentences:  23%|██▎       | 146/648 [11:39<34:32,  4.13s/it]
Embedding sentences:  23%|██▎       | 147/648 [11:45<38:54,  4.66s/it]
Embedding sentences:  23%|██▎       | 148/648 [11:52<46:40,  5.60s/it]
Embedding sentences:  23%|██▎       | 149/648 [11:57<43:20,  5.21s/it]
Embedding sentences:  23%|██▎       | 150/648 [12:01<40:29,  4.88s/it]
Embedding sentences:  23%|██▎       | 151/648 [12:09<49:54,  6.03s/it]
Embedding sentences:  23%|██▎       | 152/648 [12:13<44:02,  5.33s/it]
Embedding sentences:  24%|██▎       | 153/648 [12:16<38:26,  4.66s/it]
Embedding sentences:  24%|██▍       | 154/648 [12:19<34:45,  4.22s/it]
Embedding sentences:  24%|██▍       | 155/648 [12:28<45:43,  5.57s/it]
Embedding sentences:  24%|██▍       | 156/648 [12:33<42:46,  5.22s/it]
Embedding sentences:  24%|██▍       | 157/648 [12:36<38:28,  4.70s/it]
Embedding sentences:  24%|██▍       | 158/648 [12:40<36:25,  4.46s/it]
Embedding sentences:  25%|██▍       | 159/648 [12:43<33:01,  4.05s/it]
Embedding sentences:  25%|██▍       | 160/648 [12:48<35:59,  4.43s/it]
Embedding sentences:  25%|██▍       | 161/648 [12:54<37:48,  4.66s/it]
Embedding sentences:  25%|██▌       | 162/648 [12:57<34:11,  4.22s/it]
Embedding sentences:  25%|██▌       | 163/648 [13:02<36:58,  4.57s/it]
Embedding sentences:  25%|██▌       | 164/648 [13:05<33:20,  4.13s/it]
Embedding sentences:  25%|██▌       | 165/648 [13:08<31:00,  3.85s/it]
Embedding sentences:  26%|██▌       | 166/648 [13:18<44:18,  5.52s/it]
Embedding sentences:  26%|██▌       | 167/648 [13:22<40:49,  5.09s/it]
Embedding sentences:  26%|██▌       | 168/648 [13:25<36:26,  4.56s/it]
Embedding sentences:  26%|██▌       | 169/648 [13:29<33:35,  4.21s/it]
Embedding sentences:  26%|██▌       | 170/648 [13:33<34:27,  4.33s/it]
Embedding sentences:  26%|██▋       | 171/648 [13:37<33:08,  4.17s/it]
Embedding sentences:  27%|██▋       | 172/648 [13:45<43:08,  5.44s/it]
Embedding sentences:  27%|██▋       | 173/648 [13:48<37:15,  4.71s/it]
Embedding sentences:  27%|██▋       | 174/648 [13:53<37:23,  4.73s/it]
Embedding sentences:  27%|██▋       | 175/648 [14:00<41:57,  5.32s/it]
Embedding sentences:  27%|██▋       | 176/648 [14:05<40:25,  5.14s/it]
Embedding sentences:  27%|██▋       | 177/648 [14:11<42:07,  5.37s/it]
Embedding sentences:  27%|██▋       | 178/648 [14:15<39:03,  4.99s/it]
Embedding sentences:  28%|██▊       | 179/648 [14:20<40:38,  5.20s/it]
Embedding sentences:  28%|██▊       | 180/648 [14:29<49:26,  6.34s/it]
Embedding sentences:  28%|██▊       | 181/648 [14:32<41:33,  5.34s/it]
Embedding sentences:  28%|██▊       | 182/648 [14:35<35:46,  4.61s/it]
Embedding sentences:  28%|██▊       | 183/648 [14:39<33:22,  4.31s/it]
Embedding sentences:  28%|██▊       | 184/648 [14:42<30:57,  4.00s/it]
Embedding sentences:  29%|██▊       | 185/648 [14:46<31:06,  4.03s/it]
Embedding sentences:  29%|██▊       | 186/648 [14:49<28:40,  3.72s/it]
Embedding sentences:  29%|██▉       | 187/648 [14:57<38:55,  5.07s/it]
Embedding sentences:  29%|██▉       | 188/648 [15:06<46:16,  6.04s/it]
Embedding sentences:  29%|██▉       | 189/648 [15:09<40:06,  5.24s/it]
Embedding sentences:  29%|██▉       | 190/648 [15:13<37:52,  4.96s/it]
Embedding sentences:  29%|██▉       | 191/648 [15:18<37:25,  4.91s/it]
Embedding sentences:  30%|██▉       | 192/648 [15:22<33:39,  4.43s/it]
Embedding sentences:  30%|██▉       | 193/648 [15:26<33:17,  4.39s/it]
Embedding sentences:  30%|██▉       | 194/648 [15:31<34:08,  4.51s/it]
Embedding sentences:  30%|███       | 195/648 [15:35<32:54,  4.36s/it]
Embedding sentences:  30%|███       | 196/648 [15:38<30:13,  4.01s/it]
Embedding sentences:  30%|███       | 197/648 [15:42<31:15,  4.16s/it]
Embedding sentences:  31%|███       | 198/648 [15:47<31:29,  4.20s/it]
Embedding sentences:  31%|███       | 199/648 [15:50<30:05,  4.02s/it]
Embedding sentences:  31%|███       | 200/648 [15:54<29:45,  3.99s/it]
Embedding sentences:  31%|███       | 201/648 [16:03<40:13,  5.40s/it]
Embedding sentences:  31%|███       | 202/648 [16:07<36:20,  4.89s/it]
Embedding sentences:  31%|███▏      | 203/648 [16:11<36:04,  4.86s/it]
Embedding sentences:  31%|███▏      | 204/648 [16:15<34:17,  4.63s/it]
Embedding sentences:  32%|███▏      | 205/648 [16:20<35:01,  4.74s/it]
Embedding sentences:  32%|███▏      | 206/648 [16:24<31:31,  4.28s/it]
Embedding sentences:  32%|███▏      | 207/648 [16:29<33:55,  4.62s/it]
Embedding sentences:  32%|███▏      | 208/648 [16:32<30:57,  4.22s/it]
Embedding sentences:  32%|███▏      | 209/648 [16:37<31:03,  4.24s/it]
Embedding sentences:  32%|███▏      | 210/648 [16:40<28:16,  3.87s/it]
Embedding sentences:  33%|███▎      | 211/648 [16:44<28:41,  3.94s/it]
Embedding sentences:  33%|███▎      | 212/648 [16:50<33:07,  4.56s/it]
Embedding sentences:  33%|███▎      | 213/648 [16:53<29:26,  4.06s/it]
Embedding sentences:  33%|███▎      | 214/648 [16:56<27:29,  3.80s/it]
Embedding sentences:  33%|███▎      | 215/648 [16:59<25:55,  3.59s/it]
Embedding sentences:  33%|███▎      | 216/648 [17:04<29:19,  4.07s/it]
Embedding sentences:  33%|███▎      | 217/648 [17:09<30:49,  4.29s/it]
Embedding sentences:  34%|███▎      | 218/648 [17:16<36:21,  5.07s/it]
Embedding sentences:  34%|███▍      | 219/648 [17:20<35:03,  4.90s/it]
Embedding sentences:  34%|███▍      | 220/648 [17:24<32:10,  4.51s/it]
Embedding sentences:  34%|███▍      | 221/648 [17:32<40:11,  5.65s/it]
Embedding sentences:  34%|███▍      | 222/648 [17:40<44:41,  6.29s/it]
Embedding sentences:  34%|███▍      | 223/648 [17:43<37:47,  5.34s/it]
Embedding sentences:  35%|███▍      | 224/648 [17:46<33:10,  4.69s/it]
Embedding sentences:  35%|███▍      | 225/648 [17:50<30:34,  4.34s/it]
Embedding sentences:  35%|███▍      | 226/648 [17:53<28:05,  3.99s/it]
Embedding sentences:  35%|███▌      | 227/648 [17:59<32:28,  4.63s/it]
Embedding sentences:  35%|███▌      | 228/648 [18:04<33:10,  4.74s/it]
Embedding sentences:  35%|███▌      | 229/648 [18:11<36:34,  5.24s/it]
Embedding sentences:  35%|███▌      | 230/648 [18:14<32:01,  4.60s/it]
Embedding sentences:  36%|███▌      | 231/648 [18:20<34:39,  4.99s/it]
Embedding sentences:  36%|███▌      | 232/648 [18:26<37:31,  5.41s/it]
Embedding sentences:  36%|███▌      | 233/648 [18:29<33:02,  4.78s/it]
Embedding sentences:  36%|███▌      | 234/648 [18:38<42:06,  6.10s/it]
Embedding sentences:  36%|███▋      | 235/648 [18:42<36:38,  5.32s/it]
Embedding sentences:  36%|███▋      | 236/648 [18:45<31:45,  4.63s/it]
Embedding sentences:  37%|███▋      | 237/648 [18:48<28:45,  4.20s/it]
Embedding sentences:  37%|███▋      | 238/648 [18:51<26:13,  3.84s/it]
Embedding sentences:  37%|███▋      | 239/648 [18:55<25:28,  3.74s/it]
Embedding sentences:  37%|███▋      | 240/648 [19:01<30:14,  4.45s/it]
Embedding sentences:  37%|███▋      | 241/648 [19:05<29:39,  4.37s/it]
Embedding sentences:  37%|███▋      | 242/648 [19:14<38:10,  5.64s/it]
Embedding sentences:  38%|███▊      | 243/648 [19:17<33:56,  5.03s/it]
Embedding sentences:  38%|███▊      | 244/648 [19:21<30:33,  4.54s/it]
Embedding sentences:  38%|███▊      | 245/648 [19:24<28:11,  4.20s/it]
Embedding sentences:  38%|███▊      | 246/648 [19:29<30:32,  4.56s/it]
Embedding sentences:  38%|███▊      | 247/648 [19:33<28:56,  4.33s/it]
Embedding sentences:  38%|███▊      | 248/648 [19:42<38:00,  5.70s/it]
Embedding sentences:  38%|███▊      | 249/648 [19:45<32:55,  4.95s/it]
Embedding sentences:  39%|███▊      | 250/648 [19:50<31:56,  4.82s/it]
Embedding sentences:  39%|███▊      | 251/648 [19:53<29:14,  4.42s/it]
Embedding sentences:  39%|███▉      | 252/648 [19:59<31:54,  4.84s/it]
Embedding sentences:  39%|███▉      | 253/648 [20:03<29:34,  4.49s/it]
Embedding sentences:  39%|███▉      | 254/648 [20:06<26:58,  4.11s/it]
Embedding sentences:  39%|███▉      | 255/648 [20:12<31:00,  4.73s/it]
Embedding sentences:  40%|███▉      | 256/648 [20:16<29:29,  4.51s/it]
Embedding sentences:  40%|███▉      | 257/648 [20:19<27:02,  4.15s/it]
Embedding sentences:  40%|███▉      | 258/648 [20:23<25:07,  3.87s/it]
Embedding sentences:  40%|███▉      | 259/648 [20:26<23:45,  3.67s/it]
Embedding sentences:  40%|████      | 260/648 [20:34<31:43,  4.90s/it]
Embedding sentences:  40%|████      | 261/648 [20:37<29:06,  4.51s/it]
Embedding sentences:  40%|████      | 262/648 [20:40<25:55,  4.03s/it]
Embedding sentences:  41%|████      | 263/648 [20:49<35:37,  5.55s/it]
Embedding sentences:  41%|████      | 264/648 [20:53<32:21,  5.05s/it]
Embedding sentences:  41%|████      | 265/648 [20:58<31:12,  4.89s/it]
Embedding sentences:  41%|████      | 266/648 [21:01<28:40,  4.50s/it]
Embedding sentences:  41%|████      | 267/648 [21:11<37:43,  5.94s/it]
Embedding sentences:  41%|████▏     | 268/648 [21:14<32:13,  5.09s/it]
Embedding sentences:  42%|████▏     | 269/648 [21:23<39:21,  6.23s/it]
Embedding sentences:  42%|████▏     | 270/648 [21:26<33:20,  5.29s/it]
Embedding sentences:  42%|████▏     | 271/648 [21:30<30:49,  4.90s/it]
Embedding sentences:  42%|████▏     | 272/648 [21:36<33:10,  5.29s/it]
Embedding sentences:  42%|████▏     | 273/648 [21:42<35:31,  5.68s/it]
Embedding sentences:  42%|████▏     | 274/648 [21:47<32:50,  5.27s/it]
Embedding sentences:  42%|████▏     | 275/648 [21:54<36:44,  5.91s/it]
Embedding sentences:  43%|████▎     | 276/648 [22:03<42:34,  6.87s/it]
Embedding sentences:  43%|████▎     | 277/648 [22:07<35:50,  5.80s/it]
Embedding sentences:  43%|████▎     | 278/648 [22:13<37:02,  6.01s/it]

In [28]:
x_train_partbert.shape

(20736, 768)

In [29]:
np.save('phase2/data/X_train_parsbert.npy', x_train_partbert)
np.save('phase2/data/y_train.npy', y_train)

In [30]:
x_test_parsbert =  get_parsbert_embeddings(x_test)

Embedding sentences:   0%|          | 0/163 [00:00<?, ?it/s]/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Embedding sentences: 100%|██████████| 163/163 [12:11<00:00,  4.49s/it]

In [32]:
x_test_parsbert.shape

(5185, 768)

In [33]:
np.save('phase2/data/X_test_parsbert.npy', x_test_parsbert)
np.save('phase2/data/y_test.npy', y_train)

In [35]:
for model_name, model in models.items():
    print(f"Model: {model_name}")
    cacl_metrics(model, x_train_partbert, x_test_parsbert, y_train, y_test)

    print("-"*100)

Model: Logistic Regression

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

              precision    recall  f1-score   support

           1       0.54      0.60      0.57      1789
           2       0.33      0.18      0.24      1524
           3       0.52      0.66      0.58      1872

    accuracy                           0.50      5185
   macro avg       0.47      0.48      0.46      5185
weighted avg       0.47      0.50      0.48      5185

Accuracy:  0.49893924783027965
----------------------------------------------------------------------------------------------------
Model: SVC
              precision    recall  f1-score   support

           1       0.53      0.66      0.59      1789
           2       0.35      0.07      0.12      1524
           3       0.52      0.73      0.61      1872

    accuracy                           0.51      5185
   macro avg       0.47      0.49      0.44      5185
weighted avg       0.47      0.51      0.46      5185

Accuracy:  0.5143683702989392
----------------------------------------------------------------------------------------------------
Model: Random Forest
              precision    recall  f1-score   support

           1       0.53      0.63      0.57      1789
           2       0.35      0.15      0.21      1524
           3       0.51      0.65      0.57      1872

    accuracy                           0.50      5185
   macro avg       0.46      0.48      0.45      5185
weighted avg       0.47      0.50      0.47      5185

Accuracy:  0.4970106075216972
----------------------------------------------------------------------------------------------------
Model: KNN
              precision    recall  f1-score   support

           1       0.49      0.51      0.50      1789
           2       0.33      0.31      0.32      1524
           3       0.48      0.49      0.48      1872

    accuracy                           0.44      5185
   macro avg       0.43      0.44      0.43      5185
weighted avg       0.44      0.44      0.44      5185

Accuracy:  0.44223722275795563
----------------------------------------------------------------------------------------------------